name: Create and publish a Docker image (B)

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['main']

jobs:
  build-b:
    name: Build (B)
    runs-on: ubuntu-latest

    steps:
    - id: build-step
      name: build_step
      run: |
        date
