name: Publish Helm

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  publish-to-pages:
    permissions:
      contents: write 
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    env:
      CHART_DIR: chart
      CHART_NAME: test
    steps:
    - uses: azure/setup-helm@v3
      with:
       version: v3.11.3 
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: helm-index
        path: index
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3
    - name: Create package
      run: |
        helm package --version ${{ github.event.release.tag_name }} $CHART_DIR
    - name: Create index
      run: |
        helm repo index --url {{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }} --merge ./index/index.yaml .
        mv index.yaml index
        cd index
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add index.yaml
        git commit -m "Release ${{ github.event.release.tag_name }}"
        git push
    - name: Upload package
      run: |
        upload_url="${{ github.event.release.upload_url }}"
        upload_url=${upload_url%%\{*\}}
        file=$CHART_NAME-${{ github.event.release.tag_name }}.tgz
        echo "Uploading $file to $upload_url ..."
        curl -sSf \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: $(file -b --mime-type $file)" \
          --data-binary @$file \
          "$upload_url?name=$(basename $file)"
    - name: Upload index
      uses: actions/upload-pages-artifact@v1
      with:
        path: index
    - name: Publish index 
      id: deployment
      uses: actions/deploy-pages@v2
